apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-exporter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rancher-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "rancher-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
