{
 "title": "Rancher-Backup",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rancher Restore Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(rancher_restore_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rancher Backups Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "sum(rancher_backups_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Backups Not Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rancher_backup{status!=\"Completed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups Completed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rancher_backup{status=\"Completed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rancher_backup" }
   ]
  },
  {
   "title": "Restores",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "rancher_restore" }
   ]
  }
 ]
}