{
 "title": "Node Information",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Node to Cluster Relationships",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rancher_managed_nodes_info" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "OS",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (os) (rancher_managed_nodes_info)",
     "legendFormat": "{{ os }}"
    }
   ]
  },
  {
   "title": "K8s Role Distribution",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rancher_managed_nodes_info{is_etcd=\"true\"})",
     "legendFormat": "etcd nodes"
    },
    {
     "expr": "count(rancher_managed_nodes_info{is_control_plane=\"true\"})",
     "legendFormat": "control plane nodes"
    },
    {
     "expr": "count(rancher_managed_nodes_info{is_worker=\"true\"})",
     "legendFormat": "worker nodes"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (architecture) (rancher_managed_nodes_info)",
     "legendFormat": "{{ architecture }}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "OS Distribution",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (os_image) (rancher_managed_nodes_info)",
     "legendFormat": "{{ os_image }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (container_runtime_version) (rancher_managed_nodes_info)",
     "legendFormat": "{{ container_runtime_version }}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (kernel_version) (rancher_managed_nodes_info)",
     "legendFormat": "{{ kernel_version }}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  }
 ]
}